name: "Iterate - OpenCode Agents"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:
    inputs:
      task_type:
        description: 'Type of task to perform'
        required: true
        type: choice
        options:
          - feature
          - bugfix
          - refactor
          - test
          - docs
      file_pattern:
        description: 'File pattern to focus on (e.g., src/**/*.js)'
        required: false
        type: string

concurrency:
  group: "iterate-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: false

jobs:
  # Phase 1: Analyze Request
  analyze:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    env:
      OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    outputs:
      task_summary: ${{ steps.analyze.outputs.task_summary }}
      files_to_process: ${{ steps.analyze.outputs.files_to_process }}
      agent_branch: ${{ steps.branch.outputs.branch_name }}
    steps:

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      # Determine Event Context
      - name: Determine Event Context
        id: context
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "event_type=pr" >> $GITHUB_OUTPUT
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT
            echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
            echo "pr_body=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "event_type=push" >> $GITHUB_OUTPUT
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "event_type=manual" >> $GITHUB_OUTPUT
            echo "task_type=${{ inputs.task_type }}" >> $GITHUB_OUTPUT
            echo "file_pattern=${{ inputs.file_pattern }}" >> $GITHUB_OUTPUT
          fi

      # Branch Management
      - name: Setup Agent Branch
        id: branch
        run: |
          git fetch --all
          
          # Create timestamp-based branch name
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="agent-${TIMESTAMP}"
          
          # Create and checkout branch
          git checkout -b "$BRANCH_NAME"
          
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Created agent branch: $BRANCH_NAME"

      # Analyze Request
      - name: Analyze Task Request
        id: analyze
        env:
          EVENT_CONTEXT: |
            Event Type: ${{ steps.context.outputs.event_type }}
            PR Number: ${{ steps.context.outputs.pr_number }}
            PR URL: ${{ steps.context.outputs.pr_url }}
            PR Title: ${{ steps.context.outputs.pr_title }}
            Task Type: ${{ inputs.task_type }}
        run: |
          CONTEXT=$(cat <<'EOF'
          $EVENT_CONTEXT
          EOF
          )
          
          # Analyze using OpenCode
          RESULT=$(opencode run \
            "Analyze this GitHub event context and provide a summary:

          $CONTEXT

          Provide:
          1. Task summary (one paragraph)
          2. List of files to process (space-separated)
          
          Output only JSON: {\"task_summary\": \"...\", \"files_to_process\": \"...\"}" \
          --model opencode/kimi-k2.5-free)
          
          echo "$RESULT"
          echo "task_summary=$RESULT" >> $GITHUB_OUTPUT

  # Phase 2: Execute Agent Task
  execute:
    needs: analyze
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 120
    env:
      OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:

      # Checkout
      - name: Checkout Agent Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ needs.analyze.outputs.agent_branch }}
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      # Merge Main
      - name: Merge Latest Main
        id: merge
        continue-on-error: true
        run: |
          git checkout ${{ needs.analyze.outputs.agent_branch }}
          git merge origin/main

      # Handle Conflicts
      - name: Resolve Conflicts
        if: steps.merge.outcome == 'failure'
        run: |
          echo "Merge conflict detected"
          git merge --abort
          exit 1

      # Install OpenCode
      - name: Install OpenCode CLI
        run: |
          curl -fsSL https://opencode.ai/install | bash
          echo "$HOME/.opencode/bin" >> $GITHUB_PATH

      # Wait in Queue
      - name: Wait in Queue
        uses: softprops/turnstyle@v2
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Execute Agent
      - name: Execute OpenCode Agent
        id: agent
        continue-on-error: true
        env:
          TASK_SUMMARY: ${{ needs.analyze.outputs.task_summary }}
          FILES_TO_PROCESS: ${{ needs.analyze.outputs.files_to_process }}
        run: |
          # Execute complex multi-step task
          opencode run "$(cat <<'PROMPT'
          You are an autonomous engineering agent.

          Context:
          - Task: $TASK_SUMMARY
          - Files: $FILES_TO_PROCESS
          - Branch: agent-${TIMESTAMP}

          Task:
          1. Analyze the codebase structure
          2. Implement the required changes
          3. Run any applicable tests
          4. Ensure code quality (lint, format)
          5. Commit your changes

          Start now.
          PROMPT
          )" --model opencode/kimi-k2.5-free

      # Check Changes
      - name: Check for Changes
        id: changes
        run: |
          CHANGES=$(git status --porcelain)
          if [ -z "$CHANGES" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "$CHANGES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # Commit and Push
      - name: Commit and Push
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "Feat: ${{ needs.analyze.outputs.task_summary }}"
          git push origin ${{ needs.analyze.outputs.agent_branch }}

  # Phase 3: Create/Update PR
  finalize:
    needs: [analyze, execute]
    runs-on: ubuntu-24.04-arm
    if: always() && needs.execute.result == 'success'
    steps:

      # Checkout
      - name: Checkout Agent Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ needs.analyze.outputs.agent_branch }}
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"